spring:
  profiles: prod
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: einsetzen
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: einsetzen
    username: einsetzen
    password: einsetzen
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
#      ddl-auto: create-drop
#      ddl-auto: create
      ddl-auto: update
      generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        use_sql_comments: true
        format_sql: true

logging:
  level:
    root: WARN
    io.remedymatch: INFO
      
io:
  remedymatch:
    engine: 
      remedyRestApiUrl: einsetzen
      externalTaskUrl: einsetzen
    geodaten:
      geocoderServicebaseUrl: https://eu1.locationiq.com/v1/
      geocoderServiceApiKey: einsetzen
    keycloak:
      serverUrl: einsetzen
      user:
        realm: rmio
      client:
        realm: rmio
        username: einsetzen
        password: einsetzen
        clientId: admin-cli
        clientSecret: admin
        