on: ["push", "pull_request"]

name: Build, Test, Code Coverage

jobs:

  build:
    name: Build, Test, Code Coverage
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.4'
        java-package: jdk
        architecture: x64

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: npm install
      run: |
        npm install

    - name: Build and run test
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: clean build

    - name: Generate Code Coverage Report
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: jacocoTestReport

    - name: Upload Code Coverage Report
      uses: codecov/codecov-action@v1
      with:
        file: ./build/reports/jacoco/test/jacocoTestReport.xml